Repository PaddleHQ/paddle-go-sdk, pull requests merged in 2024-05, with the labels that each got.

#2 docs/Fix overview section
  addresses.go
  adjustments.go
  businesses.go
  currencies.go
  customers.go
  discounts.go
  events.go
  events_types.go
  ip_addresses.go
  notification_logs.go
  notification_setting_replays.go
  notification_settings.go
  notifications.go
  pkg/paddleerr/paddleerr.go
  prices.go
  pricing_preview.go
  products.go
  reports.go
  sdk.go
  shared.go
  subscriptions.go
  transactions.go
Labels: release:none, norelease

#3 Add overviews to the examples
  example_create_test.go
  example_get_test.go
  example_list_test.go
  example_update_test.go
  example_webhook_verifier_test.go
Labels: release:none, norelease

#5 Update to the latest version of httpin including omitempty
  addresses.go
  adjustments.go
  businesses.go
  currencies.go
  customers.go
  discounts.go
  events.go
  go.mod
  go.sum
  internal/client/client.go
  internal/client/client_test.go
  internal/client/directive_query.go
  notification_logs.go
  notification_settings.go
  notifications.go
  prices.go
  products.go
  reports.go
  shared.go
  subscriptions.go
  transactions.go
Labels: release:minor

#6 feat!: Add improved support for notifications and events
  CHANGELOG.md
  README.md
  collection.go
  events.go
  example_list_events_test.go
  example_test.go
  notifications.go
  pkg/paddlenotification/address.go
  pkg/paddlenotification/adjustment.go
  pkg/paddlenotification/business.go
  pkg/paddlenotification/customer.go
  pkg/paddlenotification/discount.go
  pkg/paddlenotification/notification.go
  pkg/paddlenotification/payout.go
  pkg/paddlenotification/price.go
  pkg/paddlenotification/product.go
  pkg/paddlenotification/report.go
  pkg/paddlenotification/shared.go
  pkg/paddlenotification/subscription.go
  pkg/paddlenotification/transaction.go
  testdata/events.json
Labels: release:patch

#7 Version bump - v0.3.0
  internal/client/version.txt
Labels: release:minor
